### ISSUE TITLE
R6RS document is outdated

### ISSUE THREAD

**Issue by weinholt** [schemedoc/rnrs-metadata#1]
The R6RS document in this repository does not include errata. This affects just a handful of signatures, such as `(hashtable? hashtable)` which is really `(hashtable? obj)`.

I've pushed the latest r6rs document to https://github.com/schemedoc/r6rs (the original is at bitbucket) and also pushed a branch with a fixed makefile for building the PDFs and HTML with Racket (works with Debian buster).

I'll be away at a conference for the rest of the week and will not be able to respond in a timely manner.

**Comment by lassik** [comment]
Awesome, thanks! The currently downloads the R6RS tar file from the MIT FTP site. I can update it to download https://github.com/schemedoc/r6rs/archive/master.tar.gz instead. Just have to filter the contents of the tar file to keep only the `document` directory since this new repo also contains `.tex` files in a `draft` directory which we probably don't want to index.
